# Stage 1: Build
FROM node:22-alpine AS builder

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Pass VITE_API_URL as a build argument so Vite embeds it into the JS bundle
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

# Build the TanStack Start project with Node server preset
ENV NITRO_PRESET=node-server
RUN npm run build

# Stage 2: Production
FROM node:22-alpine AS production

WORKDIR /app

# Set environment to production
ENV NODE_ENV=production

# Copy the built output from builder
COPY --from=builder /app/.output ./.output

# Run as non-root user
USER node

# Expose port
EXPOSE 3000

# Start the Node server generated by Nitro
CMD ["node", ".output/server/index.mjs"]